name: CI
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - name: Compile
        run: sbt clean test:compile
